// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/d3/scratch/kplee/Physics/TSNtuple/Analyzer/TagProbe/v04_Mu8Leg/./MakeHist_TnP_Mu8Leg_Customized.cxx";

#endif
